server:
  port: ${SERVER_PORT:8090}

spring:
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://postgres:5432/forexdb
    username: postgres
    password: 8465
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: mesuttahaguven@gmail.com  # update securely
    password: finb cfpq hcxk opth
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
  main:
    log-startup-info: false
  redis:
    host: redis
    port: 6379

logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.boot.autoconfigure.condition: ERROR
    org.springframework.boot.autoconfigure.web: ERROR
    root: INFO

calculation:
  formulas:
    path: classpath:formulas/*.groovy
  script-engine: groovy

pf2:
  rest:
    base-url: http://platform-rest:8082/api/rates/
    poll-interval: 1000
    enabled: false
    manual-mode: true

pf1:
  tcp:
    host: platform-tcp
    port: 8081
    enabled: false

coordinator:
  kafka-topic:
    forex: forex_topic
  providers:
    classes:
      - com.example.forexproject.coordinator.provider.PF2RestProvider
  alarm:
    enabled: true
    check-interval: 100000  # 10 saniye
    threshold-seconds: 300
    recipient-email: mtggamer51@gmail.com

opensearch:
  host: opensearch-node1
  port: 9200
