server:
  port: ${SERVER_PORT:8090}

spring:
  kafka:
    bootstrap-servers: localhost:29092
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@example.com  # update securely
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
  main:
    log-startup-info: false

logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.boot.autoconfigure.condition: ERROR
    org.springframework.boot.autoconfigure.web: ERROR
    root: INFO

calculation:
  formulas:
    path: classpath:formulas/*.groovy
  script-engine: groovy

pf2:
  rest:
    base-url: http://localhost:8080/api/rates/
    poll-interval: 1000
    enabled: false
    manual-mode: false

pf1:
  tcp:
    host: localhost
    port: 8081
    enabled: false

coordinator:
  kafka-topic:
    forex: forex_topic
  providers:
    classes:
      - com.example.forexproject.coordinator.provider.PF2RestProvider

sample:
  provider:
    enabled: false
